[pyprland]
plugins = [
    "scratchpads",
]

[scratchpads.filemanager]
animation = "fromLeft"
command = "uwsm-app -- thunar --name thunar-pad"
class = "thunar-pad"
margin = 100
pinned = false
size = "50% 80%"

# [scratchpads.term]
# animation = "fromTop"
# command = "kitty --class main-dropterm"
# class = "main-dropterm"
# size = "75% 60%"
# max_size = "1920px 100%"

# [scratchpads.terminals]
# animation = "fromTop"
# margin = 50
# size = "75% 60%"
# max_size = "1920px 100%"

# [scratchpads.term]
# command = "kitty --class kitty-dropterm"
# class = "^(kitty-dropterm)$"
# use = "terminals"

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "^(kitty-dropterm)$"
size = "75% 60%"
max_size = "1920px 100%"
# margin = 50
